In [111]:
import pandas as pd
from sqlalchemy import create_engine

In [112]:
pd.options.display.float_format = '{:.0f}'.format
from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()

In [113]:
data = cg.get_price(ids =[
     "Bitcoin", "Ethereum", "Tether", "XRP", "BNB", "Solana", "USDC", "Cardano", "Dogecoin", "TRON",
    "Lido Staked Ether", "Wrapped Bitcoin", "Pi Network", "LEO Token", "Chainlink", "Hedera", "Wrapped stETH",
    "USDS", "Stellar", "Avalanche", "Sui", "Litecoin", "Bitcoin Cash", "Shiba Inu", "Toncoin", "Polkadot",
    "MANTRA", "WETH", "Ethena USDe", "Bitget Token", "Hyperliquid", "Wrapped eETH", "WhiteBIT Coin", "Monero",
    "Uniswap", "Aptos", "sUSDS", "Dai", "NEAR Protocol", "Ondo", "Ethereum Classic", "Aave", "Internet Computer",
    "Pepe", "OKB", "Gate", "Coinbase Wrapped BTC", "Mantle", "Ethena", "Cronos", "Official Trump", "Tokenize Xchange",
    "VeChain", "First Digital USD", "Bittensor", "POL (ex-MATIC)", "Filecoin", "Algorand", "Fasttoken", "Lombard Staked BTC",
    "Cosmos Hub", "Celestia", "Kaspa", "Render", "Arbitrum", "Sonic (prev. FTM)", "Optimism", "KuCoin", "Jupiter",
    "Artificial Superintelligence Alliance", "Story", "Solv Protocol SolvBTC", "Binance-Peg WETH", "Movement", "Kelp DAO Restaked ETH",
    "Quant", "XDC Network", "NEXO", "DeXe", "Maker", "Rocket Pool ETH", "Usual USD", "Flare", "Stacks", "Sei", "Injective",
    "Lido DAO", "Mantle Staked Ether", "Immutable", "Theta Network", "Worldcoin", "Binance Staked SOL", "The Graph",
    "Solv Protocol SolvBTC.BBN", "Bonk", "PayPal USD", "EOS", "Tether Gold", "Tezos", "Binance Bridged USDC (BNB Smart Chain)",
    "BitTorrent", "GALA", "Wrapped BNB", "Arbitrum Bridged WBTC (Arbitrum One)", "The Sandbox", "JasmyCoin", "Jito",
    "Berachain", "IOTA", "Bitcoin SV", "Renzo Restaked ETH", "Marinade Staked SOL", "Kaia", "Stables Labs USDX",
    "BlackRock USD Institutional Digital Liquidity Fund", "Flow", "PAX Gold", "Ethereum Name Service", "FLOKI", "NEO",
    "Resolv USR", "Telcoin", "Jupiter Staked SOL", "Pyth Network", "Honey", "MultiversX", "Helium", "Ronin", "Frax",
    "TrueUSD", "Raydium", "Curve DAO", "Axie Infinity", "L2 Standard Bridged WETH (Base)", "Decentraland", "Beldex",
    "Zcash", "Mantle Restaked ETH", "Arbitrum Bridged WETH (Arbitrum One)", "pumpBTC", "Kava", "dogwifhat",
    "Bridged USDC (Polygon PoS Bridge)", "PancakeSwap", "APENFT", "Aerodrome Finance", "dYdX", "Binance-Peg Dogecoin",
    "Starknet", "THORChain", "Avalanche Bridged BTC (Avalanche)", "ether.fi Staked ETH", "Arweave", "Grass", "Conflux",
    "Onyxcoin", "Chiliz", "clBTC", "Virtuals Protocol", "OUSG", "USDB", "Hashnote USYC", "eCash", "Polygon",
    "Trust Wallet", "Core", "Ondo US Dollar Yield", "Compound", "ApeCoin", "SPX6900", "Olympus", "cgETH Hashkey Cloud",
    "Infrared Bera", "KAITO", "StakeWise Staked ETH", "tBTC", "Axelar", "Pudgy Penguins", "Amp", "Pendle", "Gnosis",
    "Mantle Bridged USDT (Mantle)", "Binance-Peg BUSD", "StakeStone Berachain Vault Token", "Verus", "Terra Luna Classic",
    "Mina Protocol", "Brett", "JUST", "AIOZ Network", "Morpho", "Elixir deUSD", "Beam", "Coinbase Wrapped Staked ETH",
    "Reserve Rights", "Polygon PoS Bridged WETH (Polygon POS)", "Plume", "1inch", "Akash Network", "Eigenlayer", "Stader ETHx",
    "Synthetix Network", "MX", "SafePal", "Frax Ether", "Theta Fuel", "Dash", "Kusama", "Swell Ethereum", "cWBTC", "Super OETH",
    "Golem", "Polygon Bridged WBTC (Polygon POS)", "Ether.fi Staked BTC", "ZKsync", "Creditcoin", "SATS (Ordinals)", "Wormhole",
    "AI Companions", "Quorium", "Fartcoin", "Blur", "Snek", "Astar", "Zilliqa", "Safe", "Basic Attention", "USDD", "Nervos Network",
    "Liquid Staked ETH", "SuperVerse", "Qtum", "Mask Network", "ai16z", "Aethir", "Livepeer", "WEMIX", "Oasis", "dYdX", "0x Protocol",
    "Fluid", "DeepBook", "VeThor", "GHO", "Notcoin", "Staked Frax Ether", "USDa", "LayerZero", "Holo", "MEOW", "CHEX Token", "Chia",
    "Celo", "Stargate Finance", "Echelon Prime", "BTSE Token", "OriginTrail", "Cheems Token", "Osmosis", "Dog (Bitcoin)", "Act I The AI Prophecy",
    "SwissBorg", "Resolv wstUSR", "Baby Doge Coin", "AgentFun.AI", "Gas", "Arkham", "Bridged Ether (StarkGate)", "Decred", "MimbleWimbleCoin",
    "aBTC", "APF coin", "Siacoin", "Acet", "NEM", "Rollbit Coin", "Treehouse ETH", "Ankr Network", "Mog Coin", "Drift Protocol", "Tribe",
    "GoMining Token", "yearn.finance", "Solayer", "DigiByte", "RCGE", "Ravencoin", "BENQI Liquid Staked AVAX", "ORDI", "Moca Network", "Popcat",
    "Elixir Staked deUSD", "aelf", "Convex Finance", "Sun Token", "Hivemapper", "cat in a dogs world", "Vana", "Enjin Coin", "Lorenzo stBTC"
], vs_currencies='usd', include_market_cap='true', include_24hr_vol='true', include_24hr_change='true', include_last_updated_at='true')

In [114]:
df = pd.DataFrame(data).transpose()
df

            usd  usd_market_cap  usd_24h_vol  usd_24h_change  last_updated_at
1inch         0       289836001     25704092              -9       1741561605
aave        178      2688765111    356741864              -9       1741561606
abtc      80538       174651125       774783              -6       1741561605
aelf          0       163585940     11424306              -8       1741561607
aethir        0       213808512     20806844             -14       1741561606
...         ...             ...          ...             ...              ...
worldcoin     0          523195           74             -19       1741561605
wormhole      0       250240267     33974063             -13       1741561611
zcash        30       476657673     56395402              -9       1741561611
zilliqa       0       224640076     14266202              -9       1741561612
zksync        0       257989449     43875498             -14       1741561611

[142 rows x 5 columns]

In [115]:
df['last_updated_at'] = pd.to_datetime(df['last_updated_at'], unit='s')

In [116]:
df

,usd,usd_market_cap,usd_24h_vol,usd_24h_change,last_updated_at
1inch,0,289836001,25704092,-9,2025-03-09 23:06:45
aave,178,2688765111,356741864,-9,2025-03-09 23:06:46
abtc,80538,174651125,774783,-6,2025-03-09 23:06:45
aelf,0,163585940,11424306,-8,2025-03-09 23:06:47
aethir,0,213808512,20806844,-14,2025-03-09 23:06:46
...,...,...,...,...,...
worldcoin,0,523195,74,-19,2025-03-09 23:06:45
wormhole,0,250240267,33974063,-13,2025-03-09 23:06:51
zcash,30,476657673,56395402,-9,2025-03-09 23:06:51
zilliqa,0,224640076,14266202,-9,2025-03-09 23:06:52
zksync,0,257989449,43875498,-14,2025-03-09 23:06:51

In [117]:
df.reset_index(inplace=True)

In [118]:
df = df.rename(columns={'index': 'coins'})

In [119]:
df.dtypes

coins                      object
usd                       float64
usd_market_cap            float64
usd_24h_vol               float64
usd_24h_change            float64
last_updated_at    datetime64[ns]
dtype: object

In [120]:
import sqlalchemy as sal
engine = sal.create_engine('mssql://Kabir-Khan-PC/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn = engine.connect()

In [125]:
df.to_sql('crypto_info', con=conn, index=False, if_exists='append')

142

In [122]:
df

,coins,usd,usd_market_cap,usd_24h_vol,usd_24h_change,last_updated_at
0,1inch,0,289836001,25704092,-9,2025-03-09 23:06:45
1,aave,178,2688765111,356741864,-9,2025-03-09 23:06:46
2,abtc,80538,174651125,774783,-6,2025-03-09 23:06:45
3,aelf,0,163585940,11424306,-8,2025-03-09 23:06:47
4,aethir,0,213808512,20806844,-14,2025-03-09 23:06:46
...,...,...,...,...,...,...
137,worldcoin,0,523195,74,-19,2025-03-09 23:06:45
138,wormhole,0,250240267,33974063,-13,2025-03-09 23:06:51
139,zcash,30,476657673,56395402,-9,2025-03-09 23:06:51
140,zilliqa,0,224640076,14266202,-9,2025-03-09 23:06:52
141,zksync,0,257989449,43875498,-14,2025-03-09 23:06:51